### PR TITLE
Keyboard Display

### LINKED ISSUE #11: As a player I want a keyboard that I can interact with.
#3

### PR DESCRIPTION
**Pull request by jvroo**
Closes #11 :

Adds keyboard HTML display buttons with relevant JS accessor function. 

@Ngewu @User1608789

### CODE REVIEW

**Review by User1608789 — CHANGES_REQUESTED** [review]
@jvroo Please add a console logger to show entered values

**Review by User1608789 — CHANGES_REQUESTED** [review]
@ Good!

**Review by User1608789 — APPROVED** [review]
Good!

**Review by Ngewu — APPROVED** [review]
Well done. Changes made are recognised

**Pull request merged**
